{{- range .Values.providers.list }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .kind }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ .replica | default 1 }}
  selector:
    matchLabels:
      app: {{ .kind }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .kind }}
        release: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ $.Values.providers.name }}
        image: "{{ $.Values.providers.image.tag }}:{{ $.Values.providers.image.version }}"
        imagePullPolicy: Always
        ports:
        - name: {{ .port_name }}
          containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_PROVIDER_KIND
          value: {{ .kind }}
        livenessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /_health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
---
{{- end }}
