apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aggregator.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: aggregator
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: aggregator
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: aggr-pod-port
