repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: kyverno
    url: https://kyverno.github.io/kyverno/
  - name: policy-reporter
    url: https://kyverno.github.io/policy-reporter
  - name: falcosecurity
    url: https://falcosecurity.github.io/charts

releases:
  # Istio (in ambient mode)
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.24.2
  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.24.2
    set:
      - name: profile
        value: ambient
  - name: istio-cni
    namespace: istio-system
    chart: istio/cni
    version: 1.24.2
    set:
      - name: profile
        value: ambient
  - name: ztunnel
    namespace: istio-system
    chart: istio/ztunnel
    version: 1.24.2

  # Mesh visualizer
  - name: kiali-server
    namespace: istio-system
    chart: kiali/kiali-server
    version: 2.2.0
    set:
      - name: auth.strategy
        value: anonymous

  # Kyverno
  - name: kyverno
    namespace: kyverno
    chart: kyverno/kyverno
    version: 3.3.4
  - name: policy-reporter
    namespace: kyverno
    chart: policy-reporter/policy-reporter
    version: 2.24.2
    set:
      - name: ui.enabled
        value: true
      - name: plugin.kyverno.enabled
        value: true

  # Falco
  - name: falco
    namespace: falco
    chart: falcosecurity/falco
    version: 4.17.0
    set:
      # Enabling real time logs
      # https://artifacthub.io/packages/helm/falcosecurity/falco#enabling-real-time-logs
      - name: tty
        value: true
      - name: driver.kind
        value: modern_ebpf
      - name: falcosidekick.enabled
        value: true
      - name: falcosidekick.webui.enabled
        value: true
