releases:
  - name: sentences-demo-app
    namespace: my-sentences-demo-app
    chart: ./sentences-demo-app/
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["label", "namespace", "{{`{{ .Release.Namespace }}`}}", "istio.io/dataplane-mode=ambient"]
