apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gw
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: istio
  listeners:
    - name: {{ .Release.Name }}-http-gw
      protocol: HTTP
      port: 80
    # - name: {{ .Release.Name }}-https-gw
    #   protocol: HTTPS
    #   port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.aggregator.name }}-httproute
spec:
  parentRefs:
    - name: {{ .Release.Name }}-gw
      namespace: {{ .Release.Namespace }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /sentence
      backendRefs:
        - name: {{ .Values.aggregator.name }}-svc
          port: 80
